Repository fktn-k/fkYAML, pull requests merged in 2024-03, with the labels that each got.

#273 #272 Fix parse error on a block sequence containing a comment within
  include/fkYAML/detail/input/deserializer.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/test_deserializer_class.cpp
Labels: bug

#274 Add workflow jobs with the macos-13 runner image
  .github/workflows/macos.yml
  README.md
  docs/mkdocs/docs/home/supported_compilers.md
Labels: enhancement

#276 #275 Fixed parse error on plain scalars containing flow indicators
  .github/workflows/ubuntu.yml
  include/fkYAML/detail/input/deserializer.hpp
  include/fkYAML/detail/input/lexical_analyzer.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/CMakeLists.txt
  test/unit_test/test_deserializer_class.cpp
  test/unit_test/test_lexical_analyzer_class.cpp
Labels: bug

#278 #277 Fixed incorrect parse result from plain scalars starting with special values
  include/fkYAML/detail/input/lexical_analyzer.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/test_lexical_analyzer_class.cpp
Labels: bug

#279 Updated documents
  README.md
  docs/mkdocs/docs/home/community_support.md
  docs/mkdocs/docs/home/supported_compilers.md
  docs/mkdocs/docs/tutorials/cmake_integration.md
Labels: documentation

#280 Clean up CMakeLists files
  CMakeLists.txt
  Makefile
  docs/examples/CMakeLists.txt
  test/cmake_add_subdirectory_test/CMakeLists.txt
  test/cmake_add_subdirectory_test/project/CMakeLists.txt
  test/cmake_fetch_content_test/CMakeLists.txt
  test/cmake_fetch_content_test/project/CMakeLists.txt
  test/cmake_find_package_test/CMakeLists.txt
  test/cmake_find_package_test/project/CMakeLists.txt
  test/cmake_target_include_directories_test/CMakeLists.txt
  test/cmake_target_include_directories_test/project/CMakeLists.txt
  test/unit_test/CMakeLists.txt
  tool/clang_tidy/CMakeLists.txt
  tool/iwyu/CMakeLists.txt
  tool/iwyu/iwyu_helper.cpp.in
Labels: enhancement

#284 #281 Fixed the parser crash due to comments right after a sequence block key
  include/fkYAML/detail/input/lexical_analyzer.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/test_deserializer_class.cpp
  test/unit_test/test_lexical_analyzer_class.cpp
Labels: bug

#287 Add .editorconfig file
  .editorconfig
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/coverage.yml
  .github/workflows/release_package.yml
  .github/workflows/windows.yml
  .reuse/README.md
  LICENSES/BSD-3-Clause.txt
  cmake/config.cmake.in
  cmake/fkYAMLConfigVersion.cmake.in
  cmake/pkg-config.pc.in
  docs/examples/ex_basic_node_operator_gt.cpp
  docs/examples/ex_basic_node_operator_lt.cpp
  docs/examples/ex_exception_constructor_msg.cpp
  docs/examples/ex_macros_versions.output
  docs/examples/example.yaml
  docs/examples/input.yaml
  docs/mkdocs/docs/api/basic_node/boolean_type.md
  docs/mkdocs/docs/api/basic_node/end.md
  docs/mkdocs/docs/api/basic_node/node_t.md
  docs/mkdocs/docs/api/basic_node/set_yaml_version.md
  docs/mkdocs/docs/api/basic_node/type.md
  docs/mkdocs/docs/home/releases.md
  docs/mkdocs/mkdocs.yml
  include/fkYAML/detail/conversions/from_node.hpp
  include/fkYAML/detail/conversions/from_string.hpp
  include/fkYAML/detail/conversions/to_node.hpp
  include/fkYAML/detail/encodings/encode_detector.hpp
  include/fkYAML/detail/encodings/encode_t.hpp
  include/fkYAML/detail/encodings/utf8_encoding.hpp
  include/fkYAML/detail/input/input_adapter.hpp
  include/fkYAML/detail/input/input_handler.hpp
  include/fkYAML/detail/macros/cpp_config_macros.hpp
  include/fkYAML/detail/meta/input_adapter_traits.hpp
  include/fkYAML/detail/meta/node_traits.hpp
  include/fkYAML/detail/meta/stl_supplement.hpp
  include/fkYAML/detail/node_property.hpp
  include/fkYAML/detail/node_ref_storage.hpp
  include/fkYAML/detail/types/lexical_token_t.hpp
  single_include/fkYAML/node.hpp
  test/cmake_add_subdirectory_test/CMakeLists.txt
  test/unit_test/test_custom_from_node.cpp
  test/unit_test/test_encode_detector.cpp
  test/unit_test/test_input_adapter.cpp
  test/unit_test/test_node_ref_storage_class.cpp
  test/unit_test/test_utf8_encoding_class.cpp
  tool/amalgamation/CHANGES.md
  tool/amalgamation/fkYAML.json
  tool/natvis_generator/Makefile
  tool/natvis_generator/README.md
  tool/natvis_generator/natvis_generator.py
Labels: enhancement

#289 #288 Fixed incorrect parse results from mapping entries split across newlines
  include/fkYAML/detail/input/deserializer.hpp
  include/fkYAML/detail/input/lexical_analyzer.hpp
  include/fkYAML/detail/types/lexical_token_t.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/test_deserializer_class.cpp
  test/unit_test/test_lexical_analyzer_class.cpp
Labels: bug

#290 Resolve warnings against using Node.js 16
  .github/workflows/amalgamation_check.yml
  .github/workflows/clang_format_check.yml
  .github/workflows/codeql.yml
  .github/workflows/coverage.yml
  .github/workflows/macos.yml
  .github/workflows/publish_docs.yml
  .github/workflows/release_package.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: ci

#291 modied the way of formatting error messages for exception objects
  include/fkYAML/detail/encodings/encode_detector.hpp
  include/fkYAML/detail/string_formatter.hpp
  include/fkYAML/detail/types/node_t.hpp
  include/fkYAML/exception.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/CMakeLists.txt
  test/unit_test/test_string_formatter.cpp
Labels: enhancement

#293 #292 Better handling for flow indicators in permitted scalar contexts
  include/fkYAML/detail/input/lexical_analyzer.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/test_deserializer_class.cpp
Labels: bug

#296 Improve handling UTF encoded inputs
  include/fkYAML/detail/encodings/encode_detector.hpp
  include/fkYAML/detail/encodings/utf_encode_t.hpp
  include/fkYAML/detail/input/deserializer.hpp
  include/fkYAML/detail/input/input_adapter.hpp
  include/fkYAML/detail/input/input_handler.hpp
  include/fkYAML/detail/input/lexical_analyzer.hpp
  include/fkYAML/detail/output/serializer.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/test_encode_detector.cpp
  test/unit_test/test_input_handler.cpp
  test/unit_test/test_lexical_analyzer_class.cpp
Labels: enhancement

#295 #297 Add a note for checking the coverage & upload the same as an artifact
  .github/workflows/coverage.yml
  CONTRIBUTING.md
  README.md
Labels: documentation, ci

#303 #302 Fixed parse error on alias mapping keys
  include/fkYAML/detail/input/deserializer.hpp
  include/fkYAML/detail/input/lexical_analyzer.hpp
  single_include/fkYAML/node.hpp
  test/unit_test/test_deserializer_class.cpp
  test/unit_test/test_lexical_analyzer_class.cpp
Labels: bug
